global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: vault-usage-exporter
    static_configs:
      - targets: ['vault-usage-exporter:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
